apiVersion: apps/v1
kind: Deployment
metadata:
  name: mt-workers
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mt-worker
  template:
    metadata:
      labels:
        app: mt-worker
    spec:
      containers:
      - name: worker
        image: mt-service:latest
        imagePullPolicy: Never
        args:
        - "-mode=worker"
        - "-redis=redis:6379"
        - "-workers=20"
        - "-kernel=15"
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        volumeMounts:
        - name: shared-data
          mountPath: /data
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-storage-pvc