apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-assembler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-assembler
  template:
    metadata:
      labels:
        app: image-assembler
    spec:
      containers:
      - name: assembler
        image: image-assembler:latest
        imagePullPolicy: IfNotPresent
        command: ["./assembler"]
        args:
          - "-redis=$(REDIS_ADDR)"
        env:
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: image-processor-config
              key: REDIS_ADDR
        volumeMounts:
        - name: shared-data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: shared-storage-pvc