apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-worker
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: image-worker
  template:
    metadata:
      labels:
        app: image-worker
    spec:
      containers:
      - name: worker
        image: image-worker:latest
        imagePullPolicy: IfNotPresent
        command: ["./worker"]
        args:
          - "-redis=$(REDIS_ADDR)"
          - "-kernel=$(KERNEL_SIZE)"
        env:
        - name: REDIS_ADDR
          valueFrom:
            configMapKeyRef:
              name: image-processor-config
              key: REDIS_ADDR
        - name: KERNEL_SIZE
          valueFrom:
            configMapKeyRef:
              name: image-processor-config
              key: KERNEL_SIZE
        resources:
          requests:
            memory: "128Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "150m"